name: CI/CD Backend Despachos

on:
  push:
    branches: ["deploy"]
    paths:
      - 'backend-despachos/**'

env:
  DOCKERHUB_NAMESPACE: goaliaga
  BACK_IMAGE: api-despachos

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login en Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" \
          | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Generar tag de imagen
        id: tags
        run: |
          VERSION="1.0.${GITHUB_RUN_NUMBER}"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Construir y publicar imagen Backend Despachos
        run: |
          IMAGE="${DOCKERHUB_NAMESPACE}/${BACK_IMAGE}"
          docker build \
            -f backend-despachos/Dockerfile \
            -t "${IMAGE}:${{ steps.tags.outputs.VERSION }}" \
            -t "${IMAGE}:latest" \
            backend-despachos
          docker push "${IMAGE}:${{ steps.tags.outputs.VERSION }}"
          docker push "${IMAGE}:latest"